# Generated by Django 4.0.4 on 2022-05-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('categoria', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Bebidas'), (2, 'Dulces'), (3, 'Lacteos')], null=True)),
                ('codigo', models.CharField(blank=True, max_length=5)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
